module.exports = async ({ nx, w, check, load, sleep, waitFor, dl, fs, path }) => {
  const D = nx.dl;
  D.items = [];
  const ses = w.active.wc ? w.active.wc.session : require('electron').session.defaultSession;
  const start = (kb, ms, name) => ses.downloadURL(`http://site.test/dl/${kb}/${ms}/${name}`);
  await load('http://site.test/');
  nx.settings.set('downloads.maxConcurrent', 2);
  start(200, 1500, 'one.bin'); start(200, 1500, 'two.bin'); start(200, 1500, 'three.bin');
  await waitFor(() => D.items.length === 3, 5000);
  check('three downloads recorded', D.items.length === 3);
  const states = D.items.map((d) => d.state);
  check('queue limits concurrency to 2', states.filter((s) => s === 'progressing').length <= 2 && states.includes('queued'), states);
  await waitFor(() => D.items.every((d) => d.state === 'completed'), 20000, 150);
  check('queued download starts and all complete', D.items.every((d) => d.state === 'completed'), D.items.map((d) => d.state));
  check('files saved with right size', D.items.every((d) => fs.existsSync(d.path) && fs.statSync(d.path).size === 200 * 1024));
  check('source domain recorded', D.items.every((d) => d.domain === 'site.test'));
  D.items = [];
  start(300, 3000, 'slow.bin');
  await waitFor(() => D.items[0] && D.items[0].state === 'progressing' && D.items[0].received > 0, 5000);
  const id = D.items[0].id;
  await D.action(id, 'pause');
  check('pause works', D.items[0].state === 'paused');
  await sleep(300);
  const r1 = D.items[0].received; await sleep(400);
  check('paused download makes no progress', D.items[0].received === r1);
  await D.action(id, 'resume');
  await waitFor(() => D.items[0].state === 'completed', 15000, 150);
  check('resume completes download', D.items[0].state === 'completed');
  start(100, 200, 'dupe.bin'); await waitFor(() => D.items.length === 2 && D.items[0].state === 'completed', 8000);
  start(100, 200, 'dupe.bin'); await waitFor(() => D.items.length === 3 && D.items[0].state === 'completed', 8000);
  const paths = D.items.filter((d) => d.name.startsWith('dupe')).map((d) => d.path);
  check('duplicate names get unique paths', new Set(paths).size === paths.length, paths);
  D.items = [];
  ses.downloadURL('http://site.test/setup.exe');
  await waitFor(() => D.items[0] && D.items[0].state === 'completed', 8000);
  check('executable flagged dangerous', D.items[0].danger && D.items[0].danger.level === 'danger', D.items[0].danger);
  nx.perm.set('http://site.test', 'downloads', 'block');
  const n = D.items.length;
  nx.perm.set('http://site.test', 'downloads', 'default');
  const before = D.items.length;
  await D.action(D.items[0].id, 'remove');
  check('remove drops entry', D.items.length === before - 1);
  nx.perm.set('http://site.test', 'downloads', 'default');
  D.clearFinished();
  check('clear completed leaves none finished', D.items.every((d) => ['progressing', 'queued', 'paused'].includes(d.state)));
  check('safeName strips path tricks', require('../../src/main/downloads').safeName('../../a‮txt.exe') === '.._.._a_txt.exe' || !/[\/\\‮]/.test(require('../../src/main/downloads').safeName('../../a‮txt.exe')));
};
